## HR Analytics Project – Employee Attrition & Workforce Insights

## 🧾Importing Libraies
Import required Python libraries for data analysis.

In [1]:
import numpy as np
import pandas as pd

## 📂Loading Dataset
The dataset is loaded using pandas for further processing.

In [2]:
data = pd.read_csv("C:/Users/shahm/OneDrive/Desktop/Project/HR_Analytics.csv")
data.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

## 🔍Data Overview and 🧹 Checking Missing Values & Duplicates
- Checked dataset structure, data types, and summary statistics.
- Verified missing values and duplicate records in the dataset.

In [3]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [4]:
data.duplicated().sum()

np.int64(7)

In [5]:
data.drop_duplicates(inplace=True)

In [6]:
data.duplicated().sum()

np.int64(0)

## 🛠 Handling Missing Values
Imputed missing values in YearsWithCurrManager using JobRole-wise median.

In [7]:
data['YearsWithCurrManager'] = data.groupby('JobRole')['YearsWithCurrManager']\
    .transform(lambda x: x.fillna(x.median()))

In [8]:
data.shape
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1473.000000,1473.000000,1473.000000,1473.000000,1473.0,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,...,1473.000000,1473.0,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000,1473.000000
mean,36.917176,802.659878,9.196877,2.911066,1.0,1026.975560,2.723693,65.833673,2.729803,2.063815,...,2.712152,80.0,0.793618,11.277665,2.800407,2.761711,7.004752,4.228106,2.183978,4.082145
std,9.130690,403.245460,8.107754,1.024612,0.0,603.223162,1.093006,20.350032,0.712115,1.106429,...,1.081575,0.0,0.851493,7.776228,1.289411,0.705838,6.121004,3.621096,3.220301,3.506696
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,492.000000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1024.000000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1558.000000,4.000000,83.000000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

## 🎯Attrition Analysis
Analyzed employee attrition distribution.

In [9]:
data['Attrition'].value_counts()

Attrition
No     1236
Yes     237
Name: count, dtype: int64

In [10]:
data['Attrition'].value_counts(normalize=True)*100

Attrition
No     83.910387
Yes    16.089613
Name: proportion, dtype: float64

## 🏢Department Analysis
Studied attrition pattern across departments.

In [11]:
pd.crosstab(data['Department'], data['Attrition'])

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  830  133
Sales                   355   92

In [12]:
pd.crosstab(data['Department'], data['Attrition'], normalize='index') * 100

Attrition                      No        Yes
Department
Human Resources         80.952381  19.047619
Research & Development  86.188993  13.811007
Sales                   79.418345  20.581655

## 💰Salary Analysis
Analyzed relationship between salary slab and attrition.

In [13]:
pd.crosstab(data['SalarySlab'], data['Attrition'])

Attrition    No  Yes
SalarySlab
10k-15k     128   20
15k+        128    5
5k-10k      392   49
Upto 5k     588  163

In [14]:
pd.crosstab(data['SalarySlab'], data['Attrition'], normalize='index') * 100

Attrition          No        Yes
SalarySlab
10k-15k     86.486486  13.513514
15k+        96.240602   3.759398
5k-10k      88.888889  11.111111
Upto 5k     78.295606  21.704394

## ⏰OverTime Analysis
Checked impact of overtime on employee attrition

In [15]:
pd.crosstab(data['OverTime'], data['Attrition'], normalize='index') * 100

Attrition         No        Yes
OverTime
No         89.593188  10.406812
Yes        69.471154  30.528846

## 👶Age Group Analysis
Analyzed attrition across different age groups.

In [16]:
pd.crosstab(data['AgeGroup'], data['Attrition'], normalize='index') * 100

Attrition         No        Yes
AgeGroup
18-25      64.227642  35.772358
26-35      80.889621  19.110379
36-45      90.851064   9.148936
46-55      88.495575  11.504425
55+        82.978723  17.021277

## 💼Job Role Analysis
Studied attrition across different job roles.

In [17]:
pd.crosstab(data['JobRole'], data['Attrition'], normalize='index') * 100

Attrition                         No        Yes
JobRole
Healthcare Representative  93.181818   6.818182
Human Resources            76.923077  23.076923
Laboratory Technician      76.153846  23.846154
Manager                    95.098039   4.901961
Manufacturing Director     93.103448   6.896552
Research Director          97.500000   2.500000
Research Scientist         83.904110  16.095890
Sales Executive            82.515337  17.484663
Sales Representative       60.714286  39.285714

## 💵Income Analysis
Compared income levels between employees who stayed vs left.

In [18]:
data.groupby('Attrition')['MonthlyIncome'].mean()

Attrition
No     6828.718447
Yes    4787.092827
Name: MonthlyIncome, dtype: float64

## 🔧 Feature Engineering

Created new features for better analysis.

In [19]:
data['Attrition_Flag'] = data['Attrition'].map({'Yes':1, 'No':0})

In [20]:
data['Income_Level'] = pd.qcut(data['MonthlyIncome'], 3, labels=['Low','Medium','High'])

In [21]:
data.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition_Flag,Income_Level
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,0,0,2,3,0,0,0,0.0,1,Low
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,0,0,2,3,0,0,0,0.0,0,Low
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,0,0,3,3,0,0,0,0.0,1,Low
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,0,0,2,3,0,0,0,0.0,0,Low
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,0,0,0,3,0,0,0,0.0,1,Low

In [22]:
data['Income_Level'].value_counts()

Income_Level
Low       491
Medium    491
High      491
Name: count, dtype: int64

## 💾Save Clean Dataset
Exported final cleaned dataset for Power BI visualization.

In [23]:
data.to_csv("C:/Users/shahm/OneDrive/Desktop/Project/HR_Final_Clean_Data.csv", index=False)

## 🚀Final Outcome

This project identifies key factors influencing employee attrition and provides actionable insights for HR decision-making.